export type CategoryKey =
  | "Apparel"
  | "Bags"
  | "Electronics"
  | "Home Appliances"
  | "Premium Gifts"
  | "Water Bottles";

export type Product = {
  id: number;
  name: string;
  sub: string;
  desc: string;
  badge?: string;
  img: string;
};

export const BS_SECTIONS = [
  { id: "t-shirts", label: "T-Shirts", start: 1, end: 36 },
  { id: "round-neck-t-shirts", label: "Round Neck T-Shirts", start: 37, end: 42 },
  { id: "shirts", label: "Shirts", start: 43, end: 50 },
  { id: "jackets", label: "Jackets", start: 51, end: 66 },
  { id: "track-pants", label: "Track Pants", start: 67, end: 69 },
  { id: "sling-bags", label: "Sling Bags", start: 70, end: 72 },
  { id: "backpacks", label: "Backpacks", start: 73, end: 79 },
  { id: "duffle-bags", label: "Duffle Bags", start: 80, end: 86 },
  { id: "file-cases", label: "File Cases", start: 87, end: 92 },
  { id: "accessories", label: "Accessories", start: 93, end: 97 },
] as const;

export const BS_HIDDEN_PAGES = new Set([1, 30, 97]);

export function slugifySegment(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function getCategorySlug(category: CategoryKey) {
  return slugifySegment(category);
}

export function getProductSlug(product: Product) {
  return slugifySegment(product.name);
}

export function getProductHref(category: CategoryKey, product: Product) {
  return `/products/${getCategorySlug(category)}/${getProductSlug(product)}`;
}

export function getCategoryBySlug(categorySlug: string) {
  return (Object.keys(CAT) as CategoryKey[]).find((category) => getCategorySlug(category) === categorySlug) ?? null;
}

export function getProductBySlug(category: CategoryKey, productSlug: string) {
  return PRODS[category].find((product) => getProductSlug(product) === productSlug) ?? null;
}

export function getBsSectionById(sectionId: string) {
  return BS_SECTIONS.find((section) => section.id === sectionId) ?? null;
}

export function getBsSectionHref(sectionId: string) {
  return `/products/apparel/bs/${sectionId}`;
}

export const BS_GALLERY_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0001_cevnam",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0002_ejzvtb",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0003_s4bzye",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0004_vfi1sy",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0005_qzyw9d",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0006_kmpeye",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0007_nhfncg",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0008_xprmar",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0009_axa4wc",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0010_hejjvf",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0011_tmsrfk",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0012_cnvumh",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0013_htzpmd",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0014_u3t0mu",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0015_oevwtd",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0016_elsmc3",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0017_rovbct",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0018_jptvq3",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0019_ghw1zn",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0020_a8t7nv",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0021_ijg5pv",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0022_x94vho",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0023_piryrz",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0024_n59tdg",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0025_w8lz14",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0026_grt65u",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0027_exqpkn",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0028_hqas4s",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0029_vznlpa",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0030_sixguc",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0031_uiiz2t",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0032_jpdxaq",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0033_wqx6dm",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0034_lbieoo",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0035_itzrrt",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0036_sfeheu",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0037_tgld8t",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0038_sp8occ",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0039_brqqbi",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0040_k6tpf1",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0041_v8l2lg",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0042_byqivv",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0043_fhwoor",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0044_xczj7l",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0045_simq7a",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0046_dy0eg2",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0047_cb2k5z",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0048_skukde",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0049_azgvd4",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0050_ajoggk",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0051_ickypa",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0052_lwk2ys",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0053_tmvdjh",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0054_njaq0n",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0055_lvmonw",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0056_mygaxt",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0057_t0sxzs",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0058_p3wih6",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0059_ub6fw4",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0060_caqrca",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0061_rgiqer",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0062_qmthvg",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0063_dmxe5z",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0064_tkmdjf",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0065_vw9vpz",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0066_qozsft",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0067_w6dfia",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0068_dwla6p",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0069_cctnma",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0070_d8he14",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0071_wv0fba",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0072_h2mqwf",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0073_i56nbv",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0074_vxiazt",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0075_zccyrr",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0076_ovi8sb",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0077_zcat2h",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0078_r9htfq",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0079_a4fk3x",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0080_lkomq5",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0081_l7sc5v",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0082_vikarw",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0083_xcngmb",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0084_zcujpk",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0085_haslpk",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0086_yruuiz",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0087_faiyw2",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0088_qsqf96",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0089_ubaacx",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0090_re5res",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0091_uidsjj",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0092_gpsid6",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0093_axyzzv",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0094_ku6szc",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0095_tgcxfu",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0096_pzxuyo",
  "https://res.cloudinary.com/diezixk4v/image/upload/BS_-_Stocks_17th_Aug_2024_1__page-0097_zyj0kq",
];

const APPAREL_IMAGE =
  "https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=900&q=80";
const APPAREL_IMAGE_2 =
  "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=900&q=80";
const APPAREL_IMAGE_3 =
  "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=900&q=80";
const BAGS_IMAGE =
  "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80";
const BAGS_IMAGE_2 =
  "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80";
const BAGS_IMAGE_3 =
  "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80";
const ELECTRONICS_IMAGE =
  "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80";
const ELECTRONICS_IMAGE_2 =
  "https://images.unsplash.com/photo-1546435770-a3e736b19889?auto=format&fit=crop&w=900&q=80";
const ELECTRONICS_IMAGE_3 =
  "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80";
const HOME_APPLIANCES_IMAGE =
  "https://images.unsplash.com/photo-1745166439895-3e6126e18370?auto=format&fit=crop&w=900&q=80";
const PREMIUM_GIFTS_IMAGE =
  "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80";
const PREMIUM_GIFTS_IMAGE_2 =
  "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=900&q=80";
const PREMIUM_GIFTS_IMAGE_3 =
  "https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?auto=format&fit=crop&w=900&q=80";
const WATER_BOTTLES_IMAGE =
  "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80";
const WATER_BOTTLES_IMAGE_2 =
  "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=900&q=80";
const WATER_BOTTLES_IMAGE_3 =
  "https://images.unsplash.com/photo-1556195332-95503f664ced?auto=format&fit=crop&w=900&q=80";

export const CAT: Record<
  CategoryKey,
  { subs: string[]; col: string; cnt: number; img: string }
> = {
  Apparel: {
    subs: ["All", "BS", "PUMA", "Rare Rabbit", "SWISS MILITARY", "Adidas", "ALLEN SOLLY", "Reebok", "VANHEUSEN", "Crocodile Polo"],
    col: "#1E3D22",
    cnt: 9,
    img: APPAREL_IMAGE,
  },
  Bags: {
    subs: ["All", "FD CAT Travel Bags", "TBB", "Artistix", "2024 Tucano", "Fur Jaden", "The House Of Creas", "Delsey Paris", "SWISS MILITARY", "Wildcraft", "Safari"],
    col: "#2D6035",
    cnt: 10,
    img: BAGS_IMAGE,
  },
  Electronics: {
    subs: ["All", "Hammer", "Ambrane", "SkullCandy", "JBL B2B", "MIVI", "Philips", "Xecch", "Blaupunkt", "Noise"],
    col: "#3A7848",
    cnt: 9,
    img: ELECTRONICS_IMAGE,
  },
  "Home Appliances": {
    subs: ["All", "Pexpo", "Prestige", "Milton", "Fourbrother", "Drinkware", "Pigeon", "Kent", "Glasafe", "B2b", "Homeapp", "Franke Faber"],
    col: "#1E3D22",
    cnt: 11,
    img: HOME_APPLIANCES_IMAGE,
  },
  "Premium Gifts": {
    subs: ["All", "Sheaffer", "Lapis Bard", "Parker", "Picassio Parri"],
    col: "#4A7254",
    cnt: 4,
    img: PREMIUM_GIFTS_IMAGE,
  },
  "Water Bottles": {
    subs: ["All", "AQUAMINDER", "Glasafe", "Artiart", "Divine Copper", "Headway", "Borosil", "B4-BOT", "Bot-All"],
    col: "#2D6035",
    cnt: 8,
    img: WATER_BOTTLES_IMAGE,
  },
};

export const PRODS: Record<CategoryKey, Product[]> = {
  Apparel: [
    {
      id: 1,
      name: "BS",
      sub: "BS",
      desc: "Premium formal shirts, crisp cotton fabric, tailored for the modern professional",
      badge: "New",
      img: BS_GALLERY_IMAGES[1],
    },
    {
      id: 2,
      name: "PUMA",
      sub: "PUMA",
      desc: "High-performance sportswear, innovative DryCELL technology, bold athletic designs",
      img: "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 3,
      name: "Rare Rabbit",
      sub: "Rare Rabbit",
      desc: "Contemporary fashion shirts, premium linen blends, resort and office-ready styles",
      img: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 4,
      name: "SWISS MILITARY",
      sub: "SWISS MILITARY",
      desc: "Durable outdoor and sports apparel, water-resistant finishes, ergonomic active cuts",
      img: "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 5,
      name: "Adidas",
      sub: "Adidas",
      desc: "Iconic sportswear tees, moisture-wicking Climalite fabric, relaxed athletic fit",
      badge: "New",
      img: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 6,
      name: "ALLEN SOLLY",
      sub: "ALLEN SOLLY",
      desc: "Classic Oxford weave shirts, button-down collar, slim tailored corporate fit",
      img: "https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 7,
      name: "Reebok",
      sub: "Reebok",
      desc: "100% cotton jersey tees, iconic Reebok branding, everyday comfort and style",
      img: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 8,
      name: "VANHEUSEN",
      sub: "VANHEUSEN",
      desc: "Fine poplin cotton shirts, wrinkle-resistant finish, tailored professional silhouette",
      img: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 9,
      name: "Crocodile Polo",
      sub: "Crocodile Polo",
      desc: "Premium pique knit polo shirts, embroidered logo, classic three-button placket",
      badge: "New",
      img: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&h=800&fit=crop&q=80",
    },
  ],

  Bags: [
    {
      id: 20,
      name: "FD CAT Travel Bags",
      sub: "FD CAT Travel Bags",
      desc: "Durable travel bags, spacious compartments, built for frequent travelers",
      badge: "New",
      img: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 21,
      name: "TBB",
      sub: "TBB",
      desc: "PU leather executive bags, quick-access document sleeve, padded laptop compartment",
      img: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 22,
      name: "Artistix",
      sub: "Artistix",
      desc: "Bold graphic backpacks, water-resistant base, 20L main compartment",
      img: "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 23,
      name: "2024 Tucano",
      sub: "2024 Tucano",
      desc: "Italian designed laptop bags, fits 15.6\" laptops, padded air-flow back panel",
      badge: "New",
      img: "https://images.unsplash.com/photo-1473188588951-666fce8e7c68?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 24,
      name: "Fur Jaden",
      sub: "Fur Jaden",
      desc: "Vegan leather accent backpacks, anti-theft back pocket, USB charging port",
      img: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 25,
      name: "The House Of Creas",
      sub: "The House Of Creas",
      desc: "Artisan-crafted backpacks, premium materials, distinctive design language",
      img: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 26,
      name: "Delsey Paris",
      sub: "Delsey Paris",
      desc: "Polycarbonate shell trolleys, 360° spinner wheels, TSA combination lock",
      img: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 27,
      name: "SWISS MILITARY",
      sub: "SWISS MILITARY",
      desc: "Military-grade nylon shell bags, reinforced zippers, spacious organized compartments",
      img: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 28,
      name: "Wildcraft",
      sub: "Wildcraft",
      desc: "30L adventure backpacks, padded laptop sleeve, ergonomic shoulder straps",
      badge: "New",
      img: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 29,
      name: "Safari",
      sub: "Safari",
      desc: "Lightweight ABS trolleys, expandable zip compartment, secure wheel housing",
      img: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=800&fit=crop&q=80",
    },
  ],

  Electronics: [
    {
      id: 40,
      name: "Hammer",
      sub: "Hammer",
      desc: "High-fidelity true wireless earbuds, deep bass drivers, foldable wireless design",
      badge: "New",
      img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 41,
      name: "Ambrane",
      sub: "Ambrane",
      desc: "20000mAh power banks, 22.5W fast charge, dual output Type-C and USB-A",
      img: "https://images.unsplash.com/photo-1585338447937-7082f8fc763d?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 42,
      name: "SkullCandy",
      sub: "SkullCandy",
      desc: "Premium over-ear headphones, sensory bass, 40hr battery, adjustable haptic feedback",
      img: "https://images.unsplash.com/photo-1546435770-a3e736b19889?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 43,
      name: "JBL B2B",
      sub: "JBL B2B",
      desc: "Professional JBL audio solutions, pure bass sound, IPX5 water-resistant designs",
      badge: "New",
      img: "https://images.unsplash.com/photo-1563330232-57114bb0823c?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 44,
      name: "MIVI",
      sub: "MIVI",
      desc: "Made in India earbuds, 13mm drivers, quad microphones, 48hr playback",
      img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 45,
      name: "Philips",
      sub: "Philips",
      desc: "Rich stereo speakers, Bluetooth 5.0, compact portable design, premium sound",
      img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 46,
      name: "Xecch",
      sub: "Xecch",
      desc: "Cutting-edge wireless earbuds, active noise cancellation, extended playtime",
      img: "https://images.unsplash.com/photo-1546435770-a3e736b19889?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 47,
      name: "Blaupunkt",
      sub: "Blaupunkt",
      desc: "360° surround sound Bluetooth speakers, IPX6 waterproof, 12hr playtime, TWS mode",
      img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 48,
      name: "Noise",
      sub: "Noise",
      desc: "Active noise cancellation earbuds, hyper sync technology, 50hr total playtime",
      img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=800&fit=crop&q=80",
    },
  ],

  "Home Appliances": [
    {
      id: 60,
      name: "Pexpo",
      sub: "Pexpo",
      desc: "Stainless steel insulated bottles and kitchenware, double-wall vacuum technology, sleek corporate gifting range",
      badge: "New",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-0_agbdzu",
    },
    {
      id: 61,
      name: "Prestige",
      sub: "Prestige",
      desc: "India's trusted kitchen appliances — pressure cookers, mixer grinders, induction cooktops, and cookware sets",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0001_bn5vvm",
    },
    {
      id: 62,
      name: "Milton",
      sub: "Milton",
      desc: "Premium insulated casseroles, lunch boxes, and water bottles, engineered for everyday freshness",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/Milton_Top_10_dealers_page-0001_fu6saq",
    },
    {
      id: 63,
      name: "Fourbrother",
      sub: "Fourbrother",
      desc: "Innovative kitchenware and drinkware solutions, modern designs crafted for the contemporary home",
      badge: "New",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0001_lttrbh",
    },
    {
      id: 64,
      name: "Drinkware",
      sub: "Drinkware",
      desc: "Curated drinkware collections — tumblers, mugs, and bottles designed for style and performance",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/drinkware_catalogue_page-0001_ysxjwl",
    },
    {
      id: 65,
      name: "Pigeon",
      sub: "Pigeon",
      desc: "Affordable and reliable kitchen appliances — LPG stoves, pressure cookers, and small appliances",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0001_dcffhn",
    },
    {
      id: 66,
      name: "Kent",
      sub: "Kent",
      desc: "RO+UV+UF water purifiers, 8L storage tank, mineral retention technology, trusted corporate gifting",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0001_anj23b",
    },
    {
      id: 67,
      name: "Glasafe",
      sub: "Glasafe",
      desc: "Crystal-clear borosilicate glass containers and bottles, premium gifting, dishwasher-safe design",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0001_nodyns",
    },
    {
      id: 68,
      name: "B2b",
      sub: "B2b",
      desc: "Exclusive B2B home appliance solutions, bulk corporate gifting, and customised product packages",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0001_ahdyoo",
    },
    {
      id: 69,
      name: "Homeapp",
      sub: "Homeapp",
      desc: "Wide range of home appliances for corporate gifting — from kitchen essentials to daily-use gadgets",
      badge: "New",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0001_gmvzxt",
    },
    {
      id: 70,
      name: "Franke Faber",
      sub: "Franke Faber",
      desc: "Swiss precision kitchen solutions, premium chimneys, sinks, faucets, and kitchen accessories",
      img: "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-0_wddnju",
    },
  ],

  "Premium Gifts": [
    {
      id: 80,
      name: "Sheaffer",
      sub: "Sheaffer",
      desc: "Glossy black lacquer rollerballs, palladium trim, premium fountain pen and ballpoint combos",
      badge: "New",
      img: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 81,
      name: "Lapis Bard",
      sub: "Lapis Bard",
      desc: "Luxury pen, card holder and cufflinks trios, gold plating, premium branded packaging",
      img: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 82,
      name: "Parker",
      sub: "Parker",
      desc: "18k gold-plated nib fountain pens, Jotter duo sets, stainless steel executive gift boxes",
      img: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 83,
      name: "Picassio Parri",
      sub: "Picassio Parri",
      desc: "Iridium-tipped fountain pen sets, ornate gift case, 3 premium ink cartridges included",
      badge: "New",
      img: "https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=600&h=800&fit=crop&q=80",
    },
  ],

  "Water Bottles": [
    {
      id: 100,
      name: "AQUAMINDER",
      sub: "AQUAMINDER",
      desc: "Hydration reminder LED, 750ml, vacuum-insulated double wall, smart bottle technology",
      badge: "New",
      img: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 101,
      name: "Glasafe",
      sub: "Glasafe",
      desc: "500ml crystal-clear borosilicate glass, anti-slip sleeve, dishwasher-safe design",
      img: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 102,
      name: "Artiart",
      sub: "Artiart",
      desc: "Suction-base innovation, 450ml borosilicate glass, non-slip desk-friendly design",
      img: "https://images.unsplash.com/photo-1571950006183-89d3c4a31e99?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 103,
      name: "Divine Copper",
      sub: "Divine Copper",
      desc: "Pure copper bottles, hand-etched floral design, Ayurvedic wellness benefits",
      badge: "New",
      img: "https://images.unsplash.com/photo-1629803915328-89ac8a9e22c0?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 104,
      name: "Headway",
      sub: "Headway",
      desc: "18/8 food-grade steel, 1L insulated, 24hr cold and 12hr hot retention, leak-proof lid",
      img: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 105,
      name: "Borosil",
      sub: "Borosil",
      desc: "Borosilicate glass bottles, protective silicone sleeve, screw-top stainless steel cap",
      img: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 106,
      name: "B4-BOT",
      sub: "B4-BOT",
      desc: "BPA-free stainless steel bottles, powder-coated finish, wide-mouth flip cap design",
      img: "https://images.unsplash.com/photo-1556195332-95503f664ced?w=600&h=800&fit=crop&q=80",
    },
    {
      id: 107,
      name: "Bot-All",
      sub: "Bot-All",
      desc: "500ml sport bottles, durable powder-coated finish, wide-mouth flip cap, BPA-free",
      img: "https://images.unsplash.com/photo-1556195332-95503f664ced?w=600&h=800&fit=crop&q=80",
    },
  ],
};

// ─── Home Appliances Brand Galleries ──────────────────────────────────────

export const HA_B2B_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0001_ahdyoo",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0002_eeocq3",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0003_r92nyz",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0004_fwbose",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0005_yahr5d",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0006_hxy0fh",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0007_xqxz4r",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0008_f6ffh6",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0009_sevu0k",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0010_nwvs5f",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0011_yy546z",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0012_vrsegw",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0013_h5o2i7",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0014_skswgx",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0015_rb4e6u",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0016_rnlhbg",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0017_ivgc24",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0018_gvuw2o",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0019_qrkt6g",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0020_js4esl",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0021_ruiyma",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0022_syvsjo",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0023_micvlz",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0024_kkid1e",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0025_xotwvl",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0026_dwiddl",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0027_iw5m4z",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0028_zmfecs",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0029_ub8wog",
  "https://res.cloudinary.com/diezixk4v/image/upload/B2b_Corporate_Catalougue_26_page-0030_tydmew",
];

export const HA_DRINKWARE_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/drinkware_catalogue_page-0001_ysxjwl",
  "https://res.cloudinary.com/diezixk4v/image/upload/drinkware_catalogue_page-0002_zeayan",
  "https://res.cloudinary.com/diezixk4v/image/upload/drinkware_catalogue_page-0003_xr5xsv",
  "https://res.cloudinary.com/diezixk4v/image/upload/drinkware_catalogue_page-0004_srv4at",
  "https://res.cloudinary.com/diezixk4v/image/upload/drinkware_catalogue_page-0005_msaflf",
  "https://res.cloudinary.com/diezixk4v/image/upload/drinkware_catalogue_page-0006_ejebvb",
  "https://res.cloudinary.com/diezixk4v/image/upload/drinkware_catalogue_page-0007_y4m2ix",
  "https://res.cloudinary.com/diezixk4v/image/upload/drinkware_catalogue_page-0008_xcxq6z",
];

export const HA_FOURBROTHER_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0001_lttrbh",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0002_kukyw8",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0003_jfndxg",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0004_ndzhnr",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0005_coxggh",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0006_cqlh1i",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0007_l6evgq",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0008_qmqcbs",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0009_kwlusq",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0010_x0la9y",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0011_wce77x",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0012_olcj7w",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0013_shjsx8",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0014_ukwju4",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0015_ilfm3e",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0016_edfv1z",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0017_xc36pq",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0018_qzacql",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0019_mngaf8",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0020_tmifiu",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0021_gtuxet",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0022_at4hbx",
  "https://res.cloudinary.com/diezixk4v/image/upload/fourbrother_catalogue_page-0023_ayywb7",
];

export const HA_GLASAFE_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0001_nodyns",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0002_sjsyjc",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0003_hjeduw",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0004_jhb271",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0005_bpkjcu",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0006_pzhgha",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0007_a1t3p6",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0008_w7iod8",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0009_zquuma",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0010_gpsexy",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0011_ebq5ym",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0012_ev3ynx",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0013_rkkdo9",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0014_in2mss",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0015_iizmgo",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0016_n4topf",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0017_zdjykm",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0018_rz0nwq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0019_nj4ftl",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0020_lgqqcp",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0021_t6oumv",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0022_qrgo8e",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0023_jsexxf",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0024_hejpgb",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0025_vmhxlx",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0026_l8ugq5",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0027_in5pwn",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0028_jlzmbu",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0029_m7vdik",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0030_yozoaf",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0031_zs6xlz",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0032_ns9njz",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0033_bejciy",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0034_g70ka3",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0035_gwnu1d",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0036_cgvrmy",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0037_p2ekdy",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0038_ymmkop",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0039_ogqfuf",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0040_nfdroq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0041_iqnbuz",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0042_mo8y3g",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0043_etbavy",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0044_qohmbj",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0045_ke1ovd",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0046_peqgj7",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0047_cymphj",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0048_dwq7vz",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0049_muaua1",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0050_vxwbwc",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0051_ig6yor",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0052_enicgw",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0053_nmnbrr",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0054_d73yty",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0055_mfoipl",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0056_tg6qkq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0057_omu88a",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0058_e9mwhu",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0059_vcesmt",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0060_upb6ro",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0061_heqej4",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0062_zouefu",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0063_cgcabt",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0064_nr0wr0",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0065_gwirk0",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0066_ffzpxq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0067_wx3u0r",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0068_tdzlfi",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0069_cozczu",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0070_pvoc0e",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0071_o8dpda",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0072_olgokl",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0073_lkpuv5",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0074_mks2hs",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0075_tnop35",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0076_voap5p",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0077_cpchak",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0078_jrftbh",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0079_qbakcf",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0080_da1o5y",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0081_uyy95a",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0082_o5ceag",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0083_zkrmx3",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0084_bqigaa",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0085_ordspl",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0086_b9ovif",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0087_ep43g7",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0088_eiqnyz",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0089_vadpee",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0090_lsalrq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Glasafe_Stock_Report_-_23-05-2026_page-0091_o8nerl",
];

export const HA_HOMEAPP_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0001_gmvzxt",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0002_wfqbwa",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0003_lteskj",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0004_vnyp8o",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0005_ih8r6r",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0006_pfyety",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0007_st2lmp",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0008_xwhffe",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0009_oyc6cf",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0010_joepmm",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0011_i0ndl7",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0012_jgxhqh",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0013_siwqdv",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0014_ln5hqa",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0015_l5zdfb",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0016_u213nx",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0017_oo2hnw",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0018_watwgp",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0019_v5ivbx",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0020_vf4i7j",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0021_fijv80",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0022_ljcbgd",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0023_phmwow",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0024_m8puvy",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0025_cqwrjt",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0026_uzfq5e",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0027_twkmau",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0028_yyitrv",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0029_gssgw5",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0030_qpvgtl",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0031_nfyjee",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0032_kasdcm",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0033_acsuo0",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0034_qmut9l",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0035_kfhhsn",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0036_svtjlh",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0037_tejlxx",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0038_dsoglr",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0039_sqt9p5",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0040_nmtsei",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0041_msnm9p",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0042_nqjyld",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0043_d0hdov",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0044_bs9j7i",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0045_ogipin",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0046_oylhu4",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0047_ituwjn",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0048_y39hq0",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0049_i45yg4",
  "https://res.cloudinary.com/diezixk4v/image/upload/Home_Appliances_6__page-0050_ljm3ec",
];

export const HA_KENT_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0001_anj23b",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0002_yjnsm2",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0003_pz79dr",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0004_u1n6t1",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0005_axgjrk",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0006_ndanxa",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0007_or1yoo",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0008_yfd3cg",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0009_ze49qt",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0010_arln1z",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0011_tgvbmd",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0012_qtxum6",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0013_k9qdkf",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0014_jbcw7y",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0015_vc8i2z",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0016_jtmeao",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0017_rabhto",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0018_a4xyfk",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0019_ydjbgk",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0020_cfrbyx",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0021_g1hfe5",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0022_kveiiv",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0023_rgfsbj",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0024_pmdwcd",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0025_jmdmeo",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0026_dvl8pv",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0027_x9psvm",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0028_znqnb3",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0029_mngxpa",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0030_rps4bv",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0031_jaykdn",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0032_lw0idl",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0033_h6o3tf",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0034_etytch",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0035_mpoqvz",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0036_npcmci",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0037_yklqpb",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0038_eupjux",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0039_nyckny",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0040_flnfzi",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0041_q8ajjq",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0042_nypqrx",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0043_z7gqdq",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0044_qpgke8",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0045_j893hj",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0046_nxj2ai",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0047_nmrdgj",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0048_fwgtdj",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0049_r7luct",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0050_yzvont",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0051_v9avc4",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0052_e1miyn",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0053_yc4dh4",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0054_er4s6j",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0055_jgmb2h",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0056_ynlq3s",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0057_s2xn56",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0058_xefa4h",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0059_il0sqp",
  "https://res.cloudinary.com/diezixk4v/image/upload/kent_april_2026_mrp.pptx_page-0060_wenl3t",
];

export const HA_MILTON_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/Milton_Top_10_dealers_page-0001_fu6saq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Milton_Top_10_dealers_page-0002_oesbph",
  "https://res.cloudinary.com/diezixk4v/image/upload/Milton_Top_10_dealers_page-0003_lfen7f",
  "https://res.cloudinary.com/diezixk4v/image/upload/Milton_Top_10_dealers_page-0004_uuz6ev",
  "https://res.cloudinary.com/diezixk4v/image/upload/Milton_Top_10_dealers_page-0005_svblt2",
];

export const HA_PEXPO_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-0_agbdzu",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-1_cp9ib5",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-2_k3qll8",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-3_byepkr",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-4_dqptuz",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-5_xbqhva",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-6_xatcgn",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-7_ckrn9m",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-8_rilplh",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-9_dq05ww",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-10_p1i9hv",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-11_exhqog",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-12_cljnfu",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-13_cqpi52",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-14_f2rdba",
  "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_catalogue_19-8-2025-images-15_dw6r8s",
];

export const HA_PRESTIGE_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0001_bn5vvm",
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0002_jxanhw",
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0003_c5lgdo",
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0004_iwaui7",
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0005_fb2vsi",
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0006_kfluao",
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0007_cefwr9",
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0008_vzp5le",
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0009_apqsmm",
  "https://res.cloudinary.com/diezixk4v/image/upload/prestige_appliance_catelogue_page-0010_xwljgo",
];

export const HA_PIGEON_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0001_dcffhn",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0002_kqdq7p",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0003_gdqlfb",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0004_sdslaf",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0005_wghil0",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0006_hwbllc",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0007_klvnca",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0008_nqpcec",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0009_bijuaa",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0010_feqdj7",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0011_uo4bk7",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0012_sff5sz",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0013_otb3m8",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0014_qkidqc",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0015_u7wqko",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0016_rcgl4m",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0017_svuf8b",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0018_qdzlmi",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0019_rnmron",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0020_z8tahk",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0021_vtdrsy",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0022_edpsis",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0023_yevhja",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0024_njhmgo",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0025_glbf75",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0026_crgiid",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0027_do31ml",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0028_thornm",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0029_vpdpi1",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0030_eqspjk",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0031_zmkmfq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0032_vr6ciz",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0033_ddt7tj",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0034_z3svec",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0035_nrfw5h",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0036_klunew",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0037_f3aetr",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0038_bc2ajx",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0039_q6qgbw",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0040_vdhpad",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0041_u6rmrc",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0042_b1si6f",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0043_ssd5w2",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0044_q43jbd",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0045_gkorex",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0046_oorthb",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0047_xdeiyt",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0048_qkzdpb",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0049_btdbkq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0050_zzda0x",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0051_fwc5mu",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0052_jyyfts",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0053_gmnhpb",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0054_bkq2jw",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0055_voophq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0056_cyzwnk",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0057_bl9cub",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0058_ohxzzw",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0059_rttjhi",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0060_k0wlch",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0061_mfnzuj",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0062_lhnj3x",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0063_bzf5ox",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0064_dmvxex",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0065_tzg8uq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0066_v1deos",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0067_ox8wmr",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0068_y9ppx0",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0069_kaqfbk",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0070_palxox",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0071_aphusq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0072_nqsozi",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0073_jsax9r",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0074_pcor45",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0075_wger2e",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0076_mljfey",
  "https://res.cloudinary.com/diezixk4v/image/upload/Pigeon_Catalogue_2025-1_page-0077_rzirhn",
];

export const HA_FRANKE_FABER_IMAGES = [
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-0_wddnju",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-1_iabnis",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-2_lthv4k",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-3_iucois",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-4_ki9kj8",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-5_ktumnw",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-6_hum2ti",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-7_dgtbp6",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-8_uww5pv",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-9_p5wl4x",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-10_zola2o",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-11_dww9ul",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-12_aaeacr",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-13_mpruxd",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-14_atibkq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-15_xx2rnl",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-16_jizd13",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-17_mduyna",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-18_br38jm",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-19_xeki7o",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-20_mis6ze",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-21_nbiq7r",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-22_udtpcp",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-23_ggtscn",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-24_fl6z0c",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-25_atixle",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-26_srogev",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-27_wbo2nh",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-28_xsw76o",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-29_twymaa",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-30_qiwxgd",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-31_hpxbng",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-32_ouro7a",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-33_mdjfl7",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-34_xdnxvk",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-35_kywls6",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-36_fuwinw",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-37_aqobh2",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-38_cthut0",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-39_x5wo6n",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-40_edibdi",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-41_botyjq",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-42_vo33nm",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-43_st1lgg",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-44_hrkarw",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-45_jsrquv",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-46_ncyhpf",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-47_tn0sg0",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-48_dosshs",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-49_lghf1s",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-50_j35ox2",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-51_i3nzv2",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-52_uh9nhr",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-53_ntswl1",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-54_w0skbl",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-55_nmdiht",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-56_ohu5ke",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-57_bcsz41",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-58_dybkr7",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-59_qaiajr",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-60_scdv0j",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-61_vfzcl7",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-62_dqnufr",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-63_u26gbg",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-64_c7crjt",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-65_q9helg",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-66_hyotdt",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-67_mpqdrm",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-68_l91lan",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-69_doxoio",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-70_jigxux",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-71_kythvg",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-72_ejka9e",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-73_sfwyj6",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-74_edssoh",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-75_ip9ivk",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-76_doqo4o",
  "https://res.cloudinary.com/diezixk4v/image/upload/Franke_Faber_B2B_Slab_Wise_Catalogue_-_2026_Final_2_2_pdfgear.com_-images-77_vrpsod",
];

export const HA_BRAND_GALLERY_MAP: Record<string, string[]> = {
  b2b:           HA_B2B_IMAGES,
  drinkware:     HA_DRINKWARE_IMAGES,
  fourbrother:   HA_FOURBROTHER_IMAGES,
  glasafe:       HA_GLASAFE_IMAGES,
  homeapp:       HA_HOMEAPP_IMAGES,
  kent:          HA_KENT_IMAGES,
  milton:        HA_MILTON_IMAGES,
  pexpo:         HA_PEXPO_IMAGES,
  prestige:      HA_PRESTIGE_IMAGES,
  pigeon:        HA_PIGEON_IMAGES,
  "franke-faber": HA_FRANKE_FABER_IMAGES,
};

export function getHaBrandImages(brandName: string): string[] | null {
  return HA_BRAND_GALLERY_MAP[slugifySegment(brandName)] ?? null;
}

export function getHaBrandHref(brandName: string): string {
  return `/products/home-appliances/${slugifySegment(brandName)}`;
}

export function getHaBrandBySlug(slug: string): Product | null {
  return PRODS["Home Appliances"].find((p) => slugifySegment(p.name) === slug) ?? null;
}

export const TICKER_ITEMS = [
  "Premium Corporate Gifting",
  "Enquire Within 24h",
  "Pan-India Delivery",
  "Curated Brand Selection",
  "Free Consultation",
  "Request a Quote",
  "New Catalogues 2024-25",
  "Bulk Order Discounts",
  "50+ Premium Brands",
  "Custom Branding Available",
];

export const HERO_SCARDS = [
  { cat: "Bags" as CategoryKey, name: "Wildcraft", img: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=300&h=180&fit=crop&q=80" },
  { cat: "Electronics" as CategoryKey, name: "JBL B2B", img: "https://images.unsplash.com/photo-1563330232-57114bb0823c?w=300&h=180&fit=crop&q=80" },
  { cat: "Apparel" as CategoryKey, name: "Crocodile Polo", img: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=300&h=180&fit=crop&q=80" },
];
