export const STORE_ASSETS = {
  logo: "https://res.cloudinary.com/diezixk4v/image/upload/Green-Roots-logo_uh01e6",
  editorialWhyUs: "https://res.cloudinary.com/diezixk4v/image/upload/whys_cde8ji",
  brands: {
    adidas: "https://res.cloudinary.com/diezixk4v/image/upload/adidas_fplm6i",
    blaupunkt: "https://res.cloudinary.com/diezixk4v/image/upload/Blaupunkt_nghc3c",
    jbl: "https://res.cloudinary.com/diezixk4v/image/upload/jbl_t3s866",
    mivi: "https://res.cloudinary.com/diezixk4v/image/upload/mivi_heowqm",
    nasher: "https://res.cloudinary.com/diezixk4v/image/upload/nahser_pilvxc",
    noise: "https://res.cloudinary.com/diezixk4v/image/upload/noise_wo4z0m",
    parker: "https://res.cloudinary.com/diezixk4v/image/upload/parker_yqpiet",
    pepe: "https://res.cloudinary.com/diezixk4v/image/upload/pepe_u1sqct",
    pexpo: "https://res.cloudinary.com/diezixk4v/image/upload/pexpo_mucptk",
    pigeon: "https://res.cloudinary.com/diezixk4v/image/upload/pigeon_onf2yl",
    prestige: "https://res.cloudinary.com/diezixk4v/image/upload/prestige_blefam",
    puma: "https://res.cloudinary.com/diezixk4v/image/upload/puma_y1plu0",
    reebok: "https://res.cloudinary.com/diezixk4v/image/upload/reebok_v6cn0a",
    safari: "https://res.cloudinary.com/diezixk4v/image/upload/safari_ef3xa4",
    sheaffer: "https://res.cloudinary.com/diezixk4v/image/upload/sheaffer_gxjep8",
    skechers: "https://res.cloudinary.com/diezixk4v/image/upload/skechers_wjxzek",
    skullcandy: "https://res.cloudinary.com/diezixk4v/image/upload/skullcandy_ekzjjk",
    toburo: "https://res.cloudinary.com/diezixk4v/image/upload/tuburo_g8tfx9",
  },
  clients: {
    lAndT: "https://res.cloudinary.com/diezixk4v/image/upload/l_t_flnajx",
    tata: "https://res.cloudinary.com/diezixk4v/image/upload/tata_rtltcc",
    vGuard: "https://res.cloudinary.com/diezixk4v/image/upload/V-Guard-Logo_zhpcw6",
    tubeInvestments: "https://res.cloudinary.com/diezixk4v/image/upload/TubeInvestments_zjdnkn",
    equitas: "https://res.cloudinary.com/diezixk4v/image/upload/equitas-small-finance-bank_df2ff8",
    kone: "https://res.cloudinary.com/diezixk4v/image/upload/kone_zkfgo1",
    chola: "https://res.cloudinary.com/diezixk4v/image/upload/chola_zb1kqk",
    tafe: "https://res.cloudinary.com/diezixk4v/image/upload/tafe_utzumx",
    premji: "https://res.cloudinary.com/diezixk4v/image/upload/premji_xoivvd",
    tataPlay: "https://res.cloudinary.com/diezixk4v/image/upload/tata-play_tbjuoi",
    tvs: "https://res.cloudinary.com/diezixk4v/image/upload/tvs_ckwhok",
    indusind: "https://res.cloudinary.com/diezixk4v/image/upload/IndusIndBankJPEGlogo_njl6lx",
    hexaware: "https://res.cloudinary.com/diezixk4v/image/upload/hexaware_ykq9b0",
    straive: "https://res.cloudinary.com/diezixk4v/image/upload/strive_dszxf2",
    axis: "https://res.cloudinary.com/diezixk4v/image/upload/axisbank_ivknsm",
    rbi: "https://res.cloudinary.com/diezixk4v/image/upload/reservebank_bhaftu",
  },
  cities: {
    Delhi: "https://res.cloudinary.com/diezixk4v/image/upload/delhinew_dyw23v",
    Mumbai: "https://res.cloudinary.com/diezixk4v/image/upload/mumbai_vfmnpt",
    Bengaluru: "https://res.cloudinary.com/diezixk4v/image/upload/bengaluru_laxz1q",
    Chennai: "https://res.cloudinary.com/diezixk4v/image/upload/chennai_ozi34i",
    Ahmedabad: "https://res.cloudinary.com/diezixk4v/image/upload/Ahmedabad_sqcbxb",
    Pune: "https://res.cloudinary.com/diezixk4v/image/upload/pune_zf7oq5",
    Kolkata: "https://res.cloudinary.com/diezixk4v/image/upload/kolkata_l2s3p3",
    Hyderabad: "https://res.cloudinary.com/diezixk4v/image/upload/hyderabad_nhesz0",
  },
} as const;
